version: "3.9"

services:
 db:
  image: arm32v7/mariadb:10.6.2-focal
  restart: always
  command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  env_file:
   - ./env/db.env
  expose:
   - 3306
  networks:
   - app_network
  volumes:
   - ./mysql_dump:/docker-entrypoint-initdb.d
   - ./mariadb_conf:/etc/mysql/conf.d
   - db_data:/var/lib/mysql
   - db_log:/var/log/mysql
  container_name: db

networks:
 app_network:

volumes:
 db_data:
 db_log:
 
