version: "3.9"

services:
 db:
  image: arm32v7/mariadb:10.6.2-focal 
  restart: always
  environment:
   MARIADB_ROOT_PASSWORD: password
   MARIADB_DATABASE: appdb
   MARIADB_USER: appdbusr
   MARIADB_PASSWORD: password
  expose:
   - 3306
  networks:
   - app_network
  volumes:
   - ./mysql_dump:/docker-entrypoint-initdb.d
   - ./mariadb_conf:/etc/mysql/conf.d
   - db_data:/var/lib/mysql
   - db_log:/var/log/mysql
  container_name: MariaDB

networks:
 app_network:

volumes:
 db_data:
 db_log:
 