name: Build and push to Docker Hub

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push bot
        uses: docker/build-push-action@v2
        with:
          context: ./bot/
          file: ./bot/Dockerfile
          platforms: linux/amd64,linux/arm
          tags: loktissimo/expense_bot:latest
          labels: ${{ steps.meta.outputs.labels }}
          push: true

      - name: Build and push webapp
        uses: docker/build-push-action@v2
        with:
          context: ./webapp/
          file: ./webapp/Dockerfile
          platforms: linux/amd64,linux/arm
          tags: loktissimo/expense_web:latest
          labels: ${{ steps.meta.outputs.labels }}
          push: true
